### ISSUE TITLE
link or .rq file?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/wp4-stories#3]
Hi @LaurensRietveld, I'll be asking this tomorrow:

In the index.html file of a datastorie there is a reference to ```query.rq```, which is a file present in the same folder as the index.html file. However, there is also the link to the SPARQL query. Why is it necessary to have both the link and the reference to the ```query.rq``` file?

**Comment by LaurensRietveld** [comment]
I'll answer this tomorrow ;) :

It's not needed to reference the `query.rq` file. Without the `query.rq` file the query from the link is used. But, what often happens when making a story is that you've settled on the visualization, but you'd like to improve the query. To avoid having to keep copy/pasting the link, you can also use the `query.rq` file to just modify the query, and overwrite the one defined in the link.
